# Generated News by Tensorflow
------------
Dataset From The publications include the New York Times, Breitbart, CNN, Business Insider, the Atlantic, Fox News, Talking Points Memo, Buzzfeed News, National Review, New York Post, the Guardian, NPR, Reuters, Vox, and the Washington Post. https://www.kaggle.com/snapcrack/all-the-news


# Requirements
------------
- Python 3.6+
- nltk with all packages
- (optional) tensorflow-gpu==2.0.0-beta1
- (optional) cudnn and cuda 10.1 

## Import Library

In [1]:
try:
  # !pip install tensorflow-gpu==2.0.0-beta1
  pass
except Exception:
  pass
import pandas as pd
import tensorflow as tf
import re
import string
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import words
from nltk.corpus import stopwords
porter = PorterStemmer()
import nltk
# uncomment line below for the first time to download the nltk packages
#nltk.download()
import numpy as np
import os
import glob
import time
tf.__version__


'2.0.0-beta1'

In [2]:
#Disable GPU for non nvidia GPU-- uncomment line below
#os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
if tf.test.gpu_device_name():
    print('GPU found')
else:
    print("No GPU found")


GPU found


## Data Preparation Function

In [3]:
tk = RegexpTokenizer(r"[a-zA-Z]+")
stop_words = set(stopwords.words('english')) 
flatten = lambda l: [item for sublist in l for item in sublist]

def remove_punc(txt):
    text = "".join([t for t in txt if t not in string.punctuation])
    return text
# Split sentense to list and remove non text
def tokenize(df):
    return tk.tokenize(text=df.lower())
#Lemmatizing to reduce inflectional forms 
lemmatizer = WordNetLemmatizer()
def word_lemmatizer(txt):
    #change to nounce
    lemtxt = [ lemmatizer.lemmatize(word,'n')  for word in txt  ]
    return lemtxt
# Stem Words

def word_stem(txt):
    stemmed = [porter.stem(word) for word in txt]
    return stemmed
def stop_word(txt):
    filtered_sentence = [] 
    for w in txt: 
        if w not in stop_words: 
            filtered_sentence.append(w) 
    return filtered_sentence 
    

## Load dataset to pandas

In [4]:
# Depend on GPU ram (word dict size) But I recommended to use 1 file first

df =[]
ar= pd.read_csv('Datasets/articles1.csv')
df.append(ar)
#ar = pd.read_csv('Datasets/articles2.csv')
#df.append(ar)
#ar = pd.read_csv('Datasets/articles3.csv')
#df.append(ar)
df = pd.concat(df, ignore_index=True,sort=False)

### Peek at Data

In [5]:
df

Unnamed: 0     id                                              title  \
0               0  17283  House Republicans Fret About Winning Their Hea...   
1               1  17284  Rift Between Officers and Residents as Killing...   
2               2  17285  Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...   
3               3  17286  Among Deaths in 2016, a Heavy Toll in Pop Musi...   
4               4  17287  Kim Jong-un Says North Korea Is Preparing to T...   
...           ...    ...                                                ...   
49995       53287  73465   Rex Tillerson Says Climate Change Is Real, but …   
49996       53288  73466  The Biggest Intelligence Questions Raised by t...   
49997       53289  73467  Trump Announces Plan That Does Little to Resol...   
49998       53290  73468    Dozens of For-Profit Colleges Could Soon Close    
49999       53291  73469                       The Milky Way’s Stolen Stars   

          publication                         author        date    year  \
0      New York Times                     Carl Hulse  2016-12-31  2016.0   
1      New York Times  Benjamin Mueller and Al Baker  2017-06-19  2017.0   
2      New York Times                   Margalit Fox  2017-01-06  2017.0   
3      New York Times               William McDonald  2017-04-10  2017.0   
4      New York Times                  Choe Sang-Hun  2017-01-02  2017.0   
...               ...                            ...         ...     ...   
49995        Atlantic                 Robinson Meyer  2017-01-11  2017.0   
49996        Atlantic                     Amy Zegart  2017-01-11  2017.0   
49997        Atlantic                  Jeremy Venook  2017-01-11  2017.0   
49998        Atlantic                    Emily DeRuy  2017-01-11  2017.0   
49999        Atlantic                   Marina Koren  2017-01-11  2017.0   

       month  url                                            content  
0       12.0  NaN  WASHINGTON  —   Congressional Republicans have...  
1        6.0  NaN  After the bullet shells get counted, the blood...  
2        1.0  NaN  When Walt Disney’s “Bambi” opened in 1942, cri...  
3        4.0  NaN  Death may be the great equalizer, but it isn’t...  
4        1.0  NaN  SEOUL, South Korea  —   North Korea’s leader, ...  
...      ...  ...                                                ...  
49995    1.0  NaN  As chairman and CEO of ExxonMobil, Rex Tillers...  
49996    1.0  NaN  I’ve spent nearly 20 years looking at intellig...  
49997    1.0  NaN    Donald Trump will not be taking necessary st...  
49998    1.0  NaN  Dozens of   colleges could be forced to close ...  
49999    1.0  NaN  The force of gravity can be described using a ...  

[50000 rows x 10 columns]

## Applied Cleansing Vocab Function

In [6]:
#df2 =  list(filter(regex.search,df['content'].head().str.cat(sep=' ').split(" "))) 200
#df2 =  df['content'].apply(lambda x: remove_punc(x)).head(1).apply(lambda x:tokenize(x)).apply(lambda x: word_lemmatizer(x)  ) #.apply(lambda x: word_stem(x))

#Number of news to load (depend on GPU ram size)
articles = 30
df2 = df['content'].apply(lambda x: remove_punc(x)).head(articles).apply(tokenize).apply(word_lemmatizer).apply(stop_word) #.apply( word_stem)
vocab = flatten(df2.values.tolist())
del df

In [7]:
vocab

['washington',
 'congressional',
 'republican',
 'new',
 'fear',
 'come',
 'health',
 'care',
 'lawsuit',
 'obama',
 'administration',
 'might',
 'win',
 'incoming',
 'trump',
 'administration',
 'could',
 'choose',
 'longer',
 'defend',
 'executive',
 'branch',
 'suit',
 'challenge',
 'administration',
 'authority',
 'spend',
 'billion',
 'dollar',
 'health',
 'insurance',
 'subsidy',
 'american',
 'handing',
 'house',
 'republican',
 'big',
 'victory',
 'issue',
 'sudden',
 'loss',
 'disputed',
 'subsidy',
 'could',
 'conceivably',
 'cause',
 'health',
 'care',
 'program',
 'implode',
 'leaving',
 'million',
 'people',
 'without',
 'access',
 'health',
 'insurance',
 'republican',
 'prepared',
 'replacement',
 'could',
 'lead',
 'chaos',
 'insurance',
 'market',
 'spur',
 'political',
 'backlash',
 'republican',
 'gain',
 'full',
 'control',
 'government',
 'stave',
 'outcome',
 'republican',
 'could',
 'find',
 'awkward',
 'position',
 'appropriating',
 'huge',
 'sum',
 'temporarily

In [8]:
#df2 = df2.map(lambda x:word_lemmatizer(x) ).map(lambda x:word_stem(x) )
 
#stem =  lambda x: word_stem(x)  
#lemma = lambda x: word_lemmatizer(x)  
#K = lemma(stem(df3))
#len(  flatten( K)) 

In [9]:
# Remove Duplcate and sort to list
vocab = list(sorted(set(vocab))) 

In [10]:
vocab

['aaron',
 'abadi',
 'abandon',
 'abandoned',
 'abates',
 'abbas',
 'abc',
 'abdulkarim',
 'abe',
 'ability',
 'able',
 'abnormal',
 'aborted',
 'absence',
 'absent',
 'absorb',
 'absurd',
 'abundant',
 'abuse',
 'abusive',
 'academy',
 'accelerate',
 'accelerated',
 'acceptable',
 'acceptance',
 'accepted',
 'access',
 'accessible',
 'accessory',
 'accidentally',
 'acclaim',
 'accommodate',
 'accomplishment',
 'accordance',
 'according',
 'accordingly',
 'account',
 'accounting',
 'accurate',
 'achieve',
 'achievement',
 'acknowledge',
 'acknowledged',
 'acknowledging',
 'acolyte',
 'acra',
 'acronym',
 'across',
 'acrylic',
 'act',
 'acted',
 'acting',
 'action',
 'active',
 'activist',
 'activity',
 'actor',
 'actress',
 'actual',
 'actually',
 'acute',
 'acutely',
 'ad',
 'adam',
 'adamantly',
 'adapting',
 'add',
 'added',
 'addendum',
 'addict',
 'adding',
 'addition',
 'additional',
 'address',
 'adequate',
 'adhere',
 'adjust',
 'adjustment',
 'adm',
 'administration',
 'admira

In [11]:
#  16179 uniq , 3662 unique char ,24638 
print ('{} unique characters'.format(len(vocab)))

6381 unique characters


In [12]:
vocab

['aaron',
 'abadi',
 'abandon',
 'abandoned',
 'abates',
 'abbas',
 'abc',
 'abdulkarim',
 'abe',
 'ability',
 'able',
 'abnormal',
 'aborted',
 'absence',
 'absent',
 'absorb',
 'absurd',
 'abundant',
 'abuse',
 'abusive',
 'academy',
 'accelerate',
 'accelerated',
 'acceptable',
 'acceptance',
 'accepted',
 'access',
 'accessible',
 'accessory',
 'accidentally',
 'acclaim',
 'accommodate',
 'accomplishment',
 'accordance',
 'according',
 'accordingly',
 'account',
 'accounting',
 'accurate',
 'achieve',
 'achievement',
 'acknowledge',
 'acknowledged',
 'acknowledging',
 'acolyte',
 'acra',
 'acronym',
 'across',
 'acrylic',
 'act',
 'acted',
 'acting',
 'action',
 'active',
 'activist',
 'activity',
 'actor',
 'actress',
 'actual',
 'actually',
 'acute',
 'acutely',
 'ad',
 'adam',
 'adamantly',
 'adapting',
 'add',
 'added',
 'addendum',
 'addict',
 'adding',
 'addition',
 'additional',
 'address',
 'adequate',
 'adhere',
 'adjust',
 'adjustment',
 'adm',
 'administration',
 'admira

In [13]:
df2

0     [washington, congressional, republican, new, f...
1     [bullet, shell, get, counted, blood, dry, voti...
2     [walt, disney, bambi, opened, critic, praised,...
3     [death, may, great, equalizer, necessarily, ev...
4     [seoul, south, korea, north, korea, leader, ki...
5     [london, queen, elizabeth, ii, ha, battling, c...
6     [beijing, president, tsai, taiwan, sharply, cr...
7     [danny, cahill, stood, slightly, dazed, blizza...
8     [hillary, kerr, founder, digital, medium, comp...
9     [angel, everywhere, mu, iz, family, apartment,...
10    [donald, j, trump, take, control, white, house...
11    [thompson, tex, one, promising, troubled, tech...
12    [west, palm, beach, fla, donald, j, trump, ran...
13    [article, part, series, aimed, helping, naviga...
14    [season, family, travel, photo, perhaps, enlar...
15    [finally, second, avenue, subway, opened, new,...
16    [page, journal, found, dylann, roof, car, asse...
17    [mumbai, india, wa, bold, risky, gamble, p

In [14]:
#Flat list 
df2 =flatten(list(df2))

## Map vocab to indices and idx to vocab

In [15]:
char2idx = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)
text_as_int = np.array([char2idx[c] for c in df2 ])

In [16]:
idx2char[12] # test

'aborted'

In [17]:
# Show how the first 13 words from the text are mapped to integers
print ('{} ---- characters mapped to int ---- > {}'.format(repr(df2[:13]), text_as_int[:13]))

['washington', 'congressional', 'republican', 'new', 'fear', 'come', 'health', 'care', 'lawsuit', 'obama', 'administration', 'might', 'win'] ---- characters mapped to int ---- > [6199 1175 4760 3787 2107 1083 2607  833 3214 3860   79 3578 6270]


In [18]:
seq_length = 100
examples_per_epoch = len(df2)//seq_length
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [19]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [20]:
# Batch size
BATCH_SIZE = 12
#BATCH_SIZE = 64
steps_per_epoch = examples_per_epoch//BATCH_SIZE

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

dataset

<BatchDataset shapes: ((12, 100), (12, 100)), types: (tf.int32, tf.int32)>

In [21]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [22]:
if tf.test.is_gpu_available():
  rnn = tf.keras.layers.LSTM
else:
  import functools
  rnn = functools.partial(
    tf.keras.layers.GRU, recurrent_activation='sigmoid')

In [23]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
    tf.keras.layers.GRU(embedding_dim, return_sequences=True),
    rnn(rnn_units,
        return_sequences=True,
        recurrent_initializer='glorot_uniform',
        stateful=True),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [24]:
model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)
optimizer = tf.optimizers.Adam()

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (12, None, 256)           1633536   
_________________________________________________________________
gru (GRU)                    (12, None, 256)           394752    
_________________________________________________________________
lstm (LSTM)                  (12, None, 1024)          5246976   
_________________________________________________________________
dense (Dense)                (12, None, 6381)          6540525   
Total params: 13,815,789
Trainable params: 13,815,789
Non-trainable params: 0
_________________________________________________________________


In [25]:
# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)
model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)
optimizer = tf.optimizers.Adam()
# Training step
EPOCHS = 100


In [26]:

for epoch in range(EPOCHS):
    start = time.time()

    # initializing the hidden state at the start of every epoch
    # initially hidden is None
    hidden = model.reset_states()

    for (batch_n, (inp, target)) in enumerate(dataset):
          with tf.GradientTape() as tape:
              # feeding the hidden state back into the model
              # This is the interesting step
              predictions = model(inp)
               
              loss = tf.nn.sparse_softmax_cross_entropy_with_logits(target, predictions)

          grads = tape.gradient(loss, model.trainable_variables)
          optimizer.apply_gradients(zip(grads, model.trainable_variables))

          if batch_n % 100 == 0:
               pass
               # print('Epoch {0} Batch {1} Loss:{2}'.format(epoch+1, batch_n, tf.print(loss)[0]))
                
               

    # saving (checkpoint) the model every 5 epochs
    if (epoch ) % 10 == 0:
      model.save_weights(checkpoint_prefix.format(epoch=epoch))
    if (epoch ) % 1000 == 0:
      model.save_weights(checkpoint_prefix.format(epoch=epoch))    
    print ('Epoch {} Loss {}'.format(epoch+1, tf.print(loss) ))
    print ('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

model.save_weights(checkpoint_prefix.format(epoch=epoch))

[[6.54943657 10.7108364 7.70784 ... 10.5168762 10.3693361 10.2134657]
 [10.002512 6.20749664 9.56113434 ... 7.54655838 6.7380805 6.65161896]
 [8.00521469 7.10256767 8.53765 ... 7.77186108 10.6190348 10.6420145]
 ...
 [8.27437592 10.8157864 7.69519615 ... 8.25664902 7.27781677 8.38977528]
 [7.05976677 10.6961632 10.5443811 ... 10.7168694 8.11445618 7.21030235]
 [8.41799259 10.861969 8.42685413 ... 7.23591423 7.75702572 6.23599911]]
Epoch 1 Loss None
Time taken for 1 epoch 4.733989715576172 sec

[[6.38502264 10.4948711 7.41504908 ... 9.99693871 9.85391808 9.85525894]
 [9.59857 5.60096931 8.7842617 ... 6.62941742 6.49822521 5.96926]
 [7.98995 6.47586918 8.18765068 ... 7.66451359 10.5180912 10.5307169]
 ...
 [8.28011703 10.1315403 7.50955772 ... 8.30326366 6.61778641 8.43718]
 [6.92724 10.4692974 10.4692974 ... 10.4679127 7.52141476 7.25957537]
 [8.26479244 10.5201693 8.61718082 ... 6.81174946 7.80237 5.61931896]]
Epoch 2 Loss None
Time taken for 1 epoch 3.1337075233459473 sec

[[6.3332324

Epoch 17 Loss None
Time taken for 1 epoch 3.145458936691284 sec

[[6.94990349 7.23079586 4.74466419 ... 2.72783017 5.04086781 3.64233065]
 [5.64099598 6.72068214 5.81548262 ... 7.63037491 4.7972517 2.78637123]
 [5.02523041 4.97282314 8.77673721 ... 5.02280521 5.30302811 6.47719336]
 ...
 [5.7414875 6.93302965 6.68001652 ... 7.26271439 4.96646118 5.71801853]
 [7.86711407 7.38784266 5.46140099 ... 6.72165 4.40627193 5.10094357]
 [7.59090805 5.42353964 6.31053 ... 3.18179464 5.95674706 6.15585089]]
Epoch 18 Loss None
Time taken for 1 epoch 3.175826072692871 sec

[[7.01301336 6.93720818 4.427598 ... 2.2177043 4.87784386 2.96989584]
 [4.55934143 7.11774397 5.09799385 ... 7.89321899 5.0425005 2.85374045]
 [4.77647305 5.52205944 9.08912277 ... 3.89585114 4.30803967 6.20414591]
 ...
 [5.76749134 6.6829977 6.15712738 ... 7.34455299 4.30615711 5.68547106]
 [7.28316 6.65055609 5.2673378 ... 7.16358232 4.3385148 4.68294287]
 [7.50850105 4.94068575 5.90525675 ... 2.7145195 5.75065136 6.21091318]]
E

Epoch 34 Loss None
Time taken for 1 epoch 3.3541200160980225 sec

[[6.6196537 0.764890432 2.58209014 ... 0.187513068 0.369360328 0.276405871]
 [0.545091271 7.35811663 0.775447 ... 6.68237686 4.01655 0.714055955]
 [1.05797303 4.69006538 3.47719765 ... 1.12632203 0.740038157 0.943118215]
 ...
 [2.67775297 0.747948229 3.82756829 ... 1.68676949 1.69956291 2.01215386]
 [5.44326496 0.801550329 0.822520614 ... 1.28055727 2.91057825 2.21572232]
 [3.75696301 0.439848334 1.95217192 ... 1.76032639 4.8741436 5.57397938]]
Epoch 35 Loss None
Time taken for 1 epoch 3.348797082901001 sec

[[6.27341652 0.303689033 2.43647051 ... 0.21846965 0.168370023 0.387735277]
 [0.626853 6.68802404 0.443937063 ... 6.60565901 3.6348722 0.742348671]
 [1.35187054 4.42041206 2.68853498 ... 1.07036638 0.0684309229 0.261787355]
 ...
 [2.75050449 0.332614839 3.2791872 ... 1.82148731 1.84920168 1.67198169]
 [4.17893124 0.407099158 0.388655096 ... 0.665747702 2.85015655 1.57810724]
 [2.22415543 0.133462593 1.67296147 ... 0.

Epoch 50 Loss None
Time taken for 1 epoch 3.387333631515503 sec

[[4.33894825 0.103226468 1.15854 ... 0.0505783595 0.0862632468 0.0518204793]
 [0.177414149 4.69633627 0.205882803 ... 4.19570637 2.14023495 0.200187773]
 [0.378974646 1.7773124 0.433857501 ... 0.24581261 0.0397165343 0.0676753]
 ...
 [0.363730282 0.0912886709 0.468643367 ... 0.309270293 0.698727131 0.196542501]
 [0.444518954 0.0470333621 0.111082479 ... 0.106217645 0.603073 0.581751108]
 [0.227719665 0.0472245254 0.230274633 ... 0.261111557 0.583768964 2.2725184]]
Epoch 51 Loss None
Time taken for 1 epoch 3.4539682865142822 sec

[[3.99035287 0.094068028 1.606251 ... 0.0489481427 0.067320846 0.0472819507]
 [0.146524712 4.50032043 0.160761625 ... 3.79857469 2.07075787 0.140642747]
 [0.281415462 1.44162834 0.604898512 ... 0.271674 0.0440365784 0.0569118708]
 ...
 [0.330354869 0.119735315 0.337012261 ... 0.23946856 0.429013908 0.249883488]
 [0.471629679 0.0444602743 0.0813450888 ... 0.121059574 0.777830064 0.580205679]
 [0.32

[[1.59557307 0.0435322449 0.419729054 ... 0.0209537186 0.0319331959 0.0241474509]
 [0.0665473193 1.75237381 0.0755486712 ... 1.42662442 0.780182958 0.0790242553]
 [0.0810426101 0.356772184 0.128730938 ... 0.116600521 0.0178200174 0.0297722872]
 ...
 [0.109708294 0.0368074477 0.140858456 ... 0.0797483474 0.210347742 0.095093]
 [0.105955511 0.0278379023 0.0355147757 ... 0.0521237776 0.284456283 0.262170464]
 [0.0912674591 0.0153675526 0.0734980181 ... 0.15529798 0.248070046 0.579642355]]
Epoch 66 Loss None
Time taken for 1 epoch 3.2886295318603516 sec

[[1.32739866 0.0256869402 0.323745161 ... 0.0186002087 0.0319596343 0.0213343259]
 [0.0626615 1.61846805 0.073839888 ... 1.10289633 0.675966263 0.0644319504]
 [0.0830762163 0.367827088 0.130816892 ... 0.0947118104 0.0151699632 0.0313841328]
 ...
 [0.10382054 0.0364657864 0.166583672 ... 0.0764613822 0.115124263 0.0988880917]
 [0.130687192 0.023588974 0.0325030722 ... 0.044238355 0.239786476 0.235511154]
 [0.061137341 0.017275922 0.06944179

Epoch 80 Loss None
Time taken for 1 epoch 3.22672963142395 sec

[[0.470469564 0.0150678074 0.14161934 ... 0.0143405553 0.0176033527 0.0167773664]
 [0.0442326516 0.401936889 0.0373341292 ... 0.567120314 0.250554472 0.0420951024]
 [0.0627291277 0.110564969 0.0638775229 ... 0.0446079262 0.00886740908 0.0139106037]
 ...
 [0.0603783205 0.015269056 0.0567548759 ... 0.043109186 0.0411085896 0.0380388908]
 [0.0330909602 0.010224347 0.0183567945 ... 0.0232398566 0.0881122947 0.0750658438]
 [0.0282471906 0.0101877674 0.0420030914 ... 0.0786506608 0.115842231 0.190469354]]
Epoch 81 Loss None
Time taken for 1 epoch 3.3947668075561523 sec

[[0.455504656 0.0130850924 0.123480029 ... 0.0127986679 0.016691437 0.0158573072]
 [0.0349025242 0.37019223 0.0320050083 ... 0.381006598 0.215221748 0.0545231737]
 [0.0481935553 0.102241233 0.0546182171 ... 0.0344588682 0.00934264157 0.0147011345]
 ...
 [0.0507544614 0.0161988065 0.0559506975 ... 0.0373319499 0.0478033721 0.0422495045]
 [0.0491078459 0.011102329 

Epoch 95 Loss None
Time taken for 1 epoch 3.2217319011688232 sec

[[0.207895949 0.00729717175 0.0682581291 ... 0.0099742813 0.0104121799 0.010595968]
 [0.0236971322 0.14503178 0.0231936164 ... 0.191862941 0.11076197 0.0326155759]
 [0.0292886067 0.0631307662 0.0338274129 ... 0.0232448652 0.00553077 0.00907002762]
 ...
 [0.0317099802 0.0106216809 0.0334234 ... 0.0219507422 0.0300724 0.0255069509]
 [0.027407106 0.00650360668 0.0118381828 ... 0.0122922231 0.049550157 0.0437601395]
 [0.0218317807 0.00591326365 0.0256495271 ... 0.040398322 0.0641758516 0.0927732438]]
Epoch 96 Loss None
Time taken for 1 epoch 3.25073504447937 sec

[[0.199105591 0.00706767943 0.0657487437 ... 0.00959558133 0.0102454685 0.0102937268]
 [0.0226657223 0.136579677 0.0223919377 ... 0.185112655 0.107156672 0.0317334235]
 [0.0282774381 0.0611607805 0.0325026102 ... 0.0225773845 0.0053806724 0.00886622816]
 ...
 [0.0306375567 0.0105406465 0.0323069915 ... 0.0211793464 0.0294135138 0.0250930525]
 [0.0274676494 0.0063370

In [27]:
# 1000 epoch, batchsize 12, 18234 vocab, appox 20 hours



# Predict

In [29]:
tf.train.latest_checkpoint(checkpoint_dir)
#tf.train.load_checkpoint(checkpoint_dir+"/ckpt_150.index")

'./training_checkpoints\\ckpt_99'

In [30]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1, None]))

In [31]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 256)            1633536   
_________________________________________________________________
gru_2 (GRU)                  (1, None, 256)            394752    
_________________________________________________________________
lstm_2 (LSTM)                (1, None, 1024)           5246976   
_________________________________________________________________
dense_2 (Dense)              (1, None, 6381)           6540525   
Total params: 13,815,789
Trainable params: 13,815,789
Non-trainable params: 0
_________________________________________________________________


In [35]:
def predict(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 300

  # Converting our start string to numbers (vectorizing)
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.9

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a multinomial distribution to predict the word returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted word as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)
       
      text_generated.append(" "+idx2char[predicted_id])

  return (start_string + ''.join(text_generated))

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 256)            1633536   
_________________________________________________________________
gru_2 (GRU)                  (1, None, 256)            394752    
_________________________________________________________________
lstm_2 (LSTM)                (1, None, 1024)           5246976   
_________________________________________________________________
dense_2 (Dense)              (1, None, 6381)           6540525   
Total params: 13,815,789
Trainable params: 13,815,789
Non-trainable params: 0
_________________________________________________________________


In [40]:
print(predict(model, start_string=u'cr'))

cr career misleadingly explosive attacked could removed book department hit problem already younger gone steady chance biggest want initiative world plant job together see song n old hawaii meltdown mother loyal video dr company photoscan attack contestant visit exercise jail like become reward drive people buy threat try including parabo see researcher department son meal mr cahill well later author taking directed told crowd collection state officiated likely camera administration people jump phase least hallway penalty want clock mu calling mean happened island stop age reagan became cower several calorie requires hard finding certain quarterback split outside friend probably arnold petraeus others group family avoid u dispute decisive day apartment kim fernandez would threat environmental november nrg selected remain veteran note detention job given cue northeast used exactly health wa started remains ignore housing show passed alongside senselessness clip smaller consume district 