# Generated News by Tensorflow
------------
Dataset From The publications include the New York Times, Breitbart, CNN, Business Insider, the Atlantic, Fox News, Talking Points Memo, Buzzfeed News, National Review, New York Post, the Guardian, NPR, Reuters, Vox, and the Washington Post. https://www.kaggle.com/snapcrack/all-the-news


# Requirements
------------
- Python 3.6+
- nltk with all packages
- (optional) tensorflow-gpu==2.0.0-beta1
- (optional) cudnn and cuda 10.1 

## Import Library

In [12]:
try:
  #!pip install tensorflow-gpu==2.0.0-beta1
  pass
except Exception:
  pass
import pandas as pd
import tensorflow as tf
import re
import string
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import words
from nltk.corpus import stopwords
from nltk.corpus import wordnet
porter = PorterStemmer()
import nltk
# uncomment line below for the first time to download the nltk packages
#nltk.download()
import numpy as np
import os
import glob
import time
tf.__version__



#http://nlp.stanford.edu/data/glove.6B.zip


from  tools.func  import main_function

In [13]:
#Disable GPU for non nvidia GPU-- uncomment line below
#os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
if tf.test.gpu_device_name():
    print('GPU found')
else:
    print("No GPU found")


GPU found


## Data Preparation Function

In [14]:
regx = r"[\“\‘\"\,’”\.]|[a-zA-Z]+" # text or , or  . 
stop_words = set(stopwords.words('english')) 
flatten = lambda l: [item for sublist in l for item in sublist]

def remove_punc(txt):
    text = "".join([t for t in txt if t not in string.punctuation])
    return text
# Split sentense to list and remove non text
def tokenize(df):
    return tk.tokenize(text=df.lower())
#Lemmatizing to reduce inflectional forms 
lemmatizer = WordNetLemmatizer()
def word_lemmatizer(txt):
    #change to nounce
    lemtxt = [ lemmatizer.lemmatize(word,'n')  for word in txt  ]
    return lemtxt
# Stem Words
 
def word_stem(txt):
    stemmed = [porter.stem(word) for word in txt]
    return stemmed
def stop_word(txt):
    filtered_sentence = [] 
    for w in txt: 
        if w not in stop_words: 
            filtered_sentence.append(w) 
    return filtered_sentence 

def filter_synsets(lsttxt):
   return [ word for word in lsttxt if len(wordnet.synsets(word))>0  ]
   
myFunc = main_function()

## Load dataset to pandas

In [15]:
# Depend on GPU ram (word dict size) But I recommended to use 1 file first

df =[]
ar= pd.read_csv('Datasets/articles1.csv')
df.append(ar)
#ar = pd.read_csv('Datasets/articles2.csv')
#df.append(ar)
#ar = pd.read_csv('Datasets/articles3.csv')
#df.append(ar)
df = pd.concat(df, ignore_index=True,sort=False)

### Peek at Data

In [16]:
df

Unnamed: 0     id                                              title  \
0               0  17283  House Republicans Fret About Winning Their Hea...   
1               1  17284  Rift Between Officers and Residents as Killing...   
2               2  17285  Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...   
3               3  17286  Among Deaths in 2016, a Heavy Toll in Pop Musi...   
4               4  17287  Kim Jong-un Says North Korea Is Preparing to T...   
...           ...    ...                                                ...   
49995       53287  73465   Rex Tillerson Says Climate Change Is Real, but …   
49996       53288  73466  The Biggest Intelligence Questions Raised by t...   
49997       53289  73467  Trump Announces Plan That Does Little to Resol...   
49998       53290  73468    Dozens of For-Profit Colleges Could Soon Close    
49999       53291  73469                       The Milky Way’s Stolen Stars   

          publication                         author        date    year  \
0      New York Times                     Carl Hulse  2016-12-31  2016.0   
1      New York Times  Benjamin Mueller and Al Baker  2017-06-19  2017.0   
2      New York Times                   Margalit Fox  2017-01-06  2017.0   
3      New York Times               William McDonald  2017-04-10  2017.0   
4      New York Times                  Choe Sang-Hun  2017-01-02  2017.0   
...               ...                            ...         ...     ...   
49995        Atlantic                 Robinson Meyer  2017-01-11  2017.0   
49996        Atlantic                     Amy Zegart  2017-01-11  2017.0   
49997        Atlantic                  Jeremy Venook  2017-01-11  2017.0   
49998        Atlantic                    Emily DeRuy  2017-01-11  2017.0   
49999        Atlantic                   Marina Koren  2017-01-11  2017.0   

       month  url                                            content  
0       12.0  NaN  WASHINGTON  —   Congressional Republicans have...  
1        6.0  NaN  After the bullet shells get counted, the blood...  
2        1.0  NaN  When Walt Disney’s “Bambi” opened in 1942, cri...  
3        4.0  NaN  Death may be the great equalizer, but it isn’t...  
4        1.0  NaN  SEOUL, South Korea  —   North Korea’s leader, ...  
...      ...  ...                                                ...  
49995    1.0  NaN  As chairman and CEO of ExxonMobil, Rex Tillers...  
49996    1.0  NaN  I’ve spent nearly 20 years looking at intellig...  
49997    1.0  NaN    Donald Trump will not be taking necessary st...  
49998    1.0  NaN  Dozens of   colleges could be forced to close ...  
49999    1.0  NaN  The force of gravity can be described using a ...  

[50000 rows x 10 columns]

## Applied Cleansing Vocab Function

In [17]:
#df2 =  list(filter(regex.search,df['content'].head().str.cat(sep=' ').split(" "))) 200
#df2 =  df['content'].apply(lambda x: remove_punc(x)).head(1).apply(lambda x:tokenize(x)).apply(lambda x: word_lemmatizer(x)  ) #.apply(lambda x: word_stem(x))

#Number of news to load (depend on GPU ram size)
articles = 5000
df2 = df['content'].sample(articles).apply(lambda x: myFunc.remove_punc(x)).apply(lambda x: myFunc.tokenize(x,regex=regx)).apply(myFunc.word_lemmatizer).apply(myFunc.stop_word).apply( filter_synsets)
vocab = flatten(df2.values.tolist())


In [18]:
vocab

['victory',
 'florida',
 'democratic',
 'party',
 'federal',
 'judge',
 'agreed',
 'wednesday',
 'extend',
 'voting',
 'registration',
 'state',
 'october',
 'impact',
 'hurricane',
 'matthew',
 'judge',
 'mark',
 'e',
 'walker',
 'u',
 'district',
 'court',
 'northern',
 'district',
 'florida',
 'granted',
 'preliminary',
 'injunction',
 'florida',
 'democratic',
 'party',
 'group',
 'argued',
 'voter',
 'registration',
 'needed',
 'moved',
 'effect',
 'storm',
 'raked',
 'along',
 'eastern',
 'coastline',
 'several',
 'day',
 'right',
 'precious',
 'voice',
 'democracy',
 'wrote',
 'walker',
 'wa',
 'appointed',
 'president',
 'wrote',
 'brief',
 'order',
 'hopefully',
 'lost',
 'right',
 'voice',
 'great',
 'country',
 'exists',
 'first',
 'place',
 'said',
 'judge',
 'noted',
 'heard',
 'testimony',
 'leon',
 'county',
 'supervisor',
 'election',
 'said',
 'magnitude',
 'storm',
 'imposed',
 'tremendous',
 'strain',
 'election',
 'office',
 'also',
 'noted',
 'storm',
 'delayed',
 

In [19]:
#df2 = df2.map(lambda x:word_lemmatizer(x) ).map(lambda x:word_stem(x) )
del df
#stem =  lambda x: word_stem(x)  
#lemma = lambda x: word_lemmatizer(x)  
#K = lemma(stem(df3))
#len(  flatten( K)) 

In [20]:
# Remove Duplcate and sort to list
vocab = list(sorted(set(vocab))) 

In [21]:
vocab

['aa',
 'aaa',
 'aachen',
 'aahs',
 'aarhus',
 'aaron',
 'aarp',
 'ab',
 'aba',
 'aback',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abashed',
 'abate',
 'abated',
 'abatement',
 'abates',
 'abating',
 'abatis',
 'abaya',
 'abbe',
 'abbey',
 'abbreviated',
 'abbreviation',
 'abc',
 'abdicate',
 'abdicating',
 'abdication',
 'abdomen',
 'abdominal',
 'abduct',
 'abducted',
 'abduction',
 'abductor',
 'abel',
 'aberdeen',
 'aberrant',
 'aberration',
 'abetted',
 'abetting',
 'abhor',
 'abhorred',
 'abhorrent',
 'abhors',
 'abide',
 'abided',
 'abides',
 'abiding',
 'abidjan',
 'ability',
 'abject',
 'abjured',
 'ablaze',
 'able',
 'ableism',
 'ably',
 'abnormal',
 'abnormality',
 'abnormally',
 'abo',
 'aboard',
 'abolish',
 'abolished',
 'abolishes',
 'abolishing',
 'abolishment',
 'abolition',
 'abolitionist',
 'abominable',
 'abominably',
 'abomination',
 'aboriginal',
 'abort',
 'aborted',
 'aborting',
 'abortion',
 'abortionist',
 'abound',
 'abounded',
 'abounds',
 

In [22]:
#  16179 uniq , 3662 unique char ,24638 
print ('{} unique characters'.format(len(vocab)))

31184 unique characters


In [23]:
vocab

['aa',
 'aaa',
 'aachen',
 'aahs',
 'aarhus',
 'aaron',
 'aarp',
 'ab',
 'aba',
 'aback',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abashed',
 'abate',
 'abated',
 'abatement',
 'abates',
 'abating',
 'abatis',
 'abaya',
 'abbe',
 'abbey',
 'abbreviated',
 'abbreviation',
 'abc',
 'abdicate',
 'abdicating',
 'abdication',
 'abdomen',
 'abdominal',
 'abduct',
 'abducted',
 'abduction',
 'abductor',
 'abel',
 'aberdeen',
 'aberrant',
 'aberration',
 'abetted',
 'abetting',
 'abhor',
 'abhorred',
 'abhorrent',
 'abhors',
 'abide',
 'abided',
 'abides',
 'abiding',
 'abidjan',
 'ability',
 'abject',
 'abjured',
 'ablaze',
 'able',
 'ableism',
 'ably',
 'abnormal',
 'abnormality',
 'abnormally',
 'abo',
 'aboard',
 'abolish',
 'abolished',
 'abolishes',
 'abolishing',
 'abolishment',
 'abolition',
 'abolitionist',
 'abominable',
 'abominably',
 'abomination',
 'aboriginal',
 'abort',
 'aborted',
 'aborting',
 'abortion',
 'abortionist',
 'abound',
 'abounded',
 'abounds',
 

In [24]:
df2

38344    [victory, florida, democratic, party, federal,...
30922    [tuesday, campaign, stop, presidential, swing,...
35322    [washington, defiant, president, trump, said, ...
32930    [president, trump, ha, announced, attend, year...
32819    [famine, south, sudan, ha, left, people, verge...
                               ...                        
31170    [german, police, union, chief, ha, blamed, mas...
15951    [monday, fox, news, channel, republican, presi...
17917    [actress, lena, ha, apologized, saying, wish, ...
46840    [extremely, secretive, silicon, valley, startu...
6766     [j, trump, candidacy, ha, driven, away, throng...
Name: content, Length: 5000, dtype: object

In [25]:
#Flat list 
df2 =flatten(list(df2))

## Map vocab to indices and idx to vocab

In [26]:
char2idx = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)
text_as_int = np.array([char2idx[c] for c in df2 ])

In [27]:
import pickle
with open('char2idx', 'wb') as fp:
    pickle.dump(char2idx, fp)
with open('idx2char', 'wb') as fp:
    pickle.dump(idx2char, fp)
    
'''
with open ('char2idx', |rb') as fp:
    char2idx = pickle.load(fp)
with open ('idx2char', 'rb') as fp:
    idx2char = pickle.load(fp)
'''

"\nwith open ('char2idx', |rb') as fp:\n    char2idx = pickle.load(fp)\nwith open ('idx2char', 'rb') as fp:\n    idx2char = pickle.load(fp)\n"

In [28]:
idx2char[12] # test

'abandoning'

In [29]:
# Show how the first 13 words from the text are mapped to integers
print ('{} ---- characters mapped to int ---- > {}'.format(repr(df2[:13]), text_as_int[:13]))

['victory', 'florida', 'democratic', 'party', 'federal', 'judge', 'agreed', 'wednesday', 'extend', 'voting', 'registration', 'state', 'october'] ---- characters mapped to int ---- > [30015 10774  7200 19696 10335 15035   599 30466  9965 30190 22599 26314
 18774]


In [30]:
seq_length = 100
examples_per_epoch = len(df2)//seq_length
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [31]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [32]:
# Batch size
BATCH_SIZE = 32
#BATCH_SIZE = 64
steps_per_epoch = examples_per_epoch//BATCH_SIZE

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

dataset

<BatchDataset shapes: ((32, 100), (32, 100)), types: (tf.int32, tf.int32)>

In [33]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [34]:
if tf.test.is_gpu_available():
  rnn = tf.keras.layers.LSTM
else:
  import functools
  rnn = functools.partial(
    tf.keras.layers.GRU, recurrent_activation='sigmoid')

In [35]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
    tf.keras.layers.GRU(embedding_dim, return_sequences=True),
    rnn(rnn_units,
        return_sequences=True,
        recurrent_initializer='glorot_uniform',
        stateful=True),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [36]:
model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)
optimizer = tf.optimizers.Adam()

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (32, None, 256)           7983104   
_________________________________________________________________
gru (GRU)                    (32, None, 256)           394752    
_________________________________________________________________
lstm (LSTM)                  (32, None, 1024)          5246976   
_________________________________________________________________
dense (Dense)                (32, None, 31184)         31963600  
Total params: 45,588,432
Trainable params: 45,588,432
Non-trainable params: 0
_________________________________________________________________


In [37]:
# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)
model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)
optimizer = tf.optimizers.Adam()
# Training step
EPOCHS = 100


In [27]:

for epoch in range(EPOCHS):
    start = time.time()

    # initializing the hidden state at the start of every epoch
    # initially hidden is None
    hidden = model.reset_states()

    for (batch_n, (inp, target)) in enumerate(dataset):
          with tf.GradientTape() as tape:
              # feeding the hidden state back into the model
              # This is the interesting step
              predictions = model(inp)
               
              loss = tf.nn.sparse_softmax_cross_entropy_with_logits(target, predictions)

          grads = tape.gradient(loss, model.trainable_variables)
          optimizer.apply_gradients(zip(grads, model.trainable_variables))

          if batch_n % 100 == 0:
               pass
               # print('Epoch {0} Batch {1} Loss:{2}'.format(epoch+1, batch_n, tf.print(loss)[0]))
                
               

    # saving (checkpoint) the model every 5 epochs
    if (epoch ) % 10 == 0:
      model.save_weights(checkpoint_prefix.format(epoch=epoch))
    if (epoch ) % 1000 == 0:
      model.save_weights(checkpoint_prefix.format(epoch=epoch))    
    print ('Epoch {} Loss {}'.format(epoch+1, tf.print(loss) ))
    print ('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

model.save_weights(checkpoint_prefix.format(epoch=epoch))

[[6.76585293 7.49940205 8.71945667 ... 8.82592392 8.1379385 8.73035717]
 [3.63649893 7.28750706 8.75119591 ... 6.36555099 3.96013355 7.67202759]
 [8.52743816 8.47812748 5.13531303 ... 4.78418398 11.3145523 7.541852]
 ...
 [11.1273022 6.56069946 7.99497318 ... 8.59057617 9.1917429 9.08055878]
 [9.77838135 8.84679794 10.7382326 ... 7.53161192 8.18411636 7.74017334]
 [9.87986565 12.7084484 9.2558136 ... 6.30616188 12.2172794 8.34352779]]
Epoch 1 Loss None
Time taken for 1 epoch 135.36069583892822 sec

[[7.75470257 7.68007803 8.64077282 ... 10.2360792 8.3498745 7.81723928]
 [2.17790437 7.16770744 8.32011604 ... 6.39916611 3.85256195 7.9908762]
 [8.73326492 8.87882614 5.56804848 ... 5.09415531 9.92994118 6.77045774]
 ...
 [10.5264912 6.27496672 7.79320431 ... 7.65872765 8.67212677 7.11261749]
 [11.1167336 8.42604733 10.252183 ... 7.62506962 8.73245811 7.17451715]
 [10.012455 11.9409485 10.0558014 ... 6.66888905 10.5261 8.28692245]]
Epoch 2 Loss None
Time taken for 1 epoch 134.19229221343994

Epoch 17 Loss None
Time taken for 1 epoch 135.0833125114441 sec

[[8.64126587 8.45386124 7.7852726 ... 7.6892662 6.62630224 3.63216233]
 [1.84457636 7.4527669 7.44959497 ... 6.02714634 3.8280766 7.01784325]
 [7.92118502 7.7794 4.45435667 ... 4.87689686 0.424667597 1.77045286]
 ...
 [3.20988226 5.86984348 6.34533215 ... 7.75153494 6.14851761 2.37529039]
 [3.31706309 0.777476132 0.48497647 ... 6.82943487 5.17878628 5.19754219]
 [7.28346157 0.00558518386 5.43753099 ... 0.656935632 0.709008813 8.16782]]
Epoch 18 Loss None
Time taken for 1 epoch 136.35378217697144 sec

[[8.89765835 8.81031418 6.97951794 ... 7.88299274 7.03751087 2.89194775]
 [1.83239806 7.45997953 7.18720722 ... 5.74051142 3.85366344 7.17604256]
 [8.16107 6.75620556 4.52181959 ... 4.40993881 1.6168859 2.57251596]
 ...
 [0.862462 5.87233829 6.94710541 ... 7.37595177 4.80884838 0.937076211]
 [2.86407232 1.66690755 1.72556031 ... 6.85535049 5.01470375 4.62907696]
 [6.23452473 0.0236216914 4.7765646 ... 0.717614114 1.55333376 7

[[10.1160412 7.40307617 7.21181774 ... 6.97816372 5.37016773 3.20790243]
 [1.59930611 8.33347511 8.45264721 ... 5.32923412 3.86000109 7.54347706]
 [11.1662788 3.87913775 3.89384937 ... 4.85936308 0.00383249694 1.90611577]
 ...
 [0.0243774783 4.59562206 5.36815357 ... 7.5356679 4.320261 2.04280567]
 [0.117208757 0.177741542 0.0900219902 ... 6.72499275 3.39761591 3.30571294]
 [3.54137897 0.00895212404 0.872359335 ... 0.639426887 0.109177031 1.27234352]]
Epoch 34 Loss None
Time taken for 1 epoch 140.09131741523743 sec

[[9.43079948 7.75098705 7.45983124 ... 5.76741028 4.02232 3.70048428]
 [1.68734598 8.99490547 7.38261 ... 5.56742764 4.3693018 7.40892363]
 [10.9849892 4.07209063 3.89792204 ... 4.4485364 0.039488975 1.4964124]
 ...
 [0.0668722764 5.38063431 5.37759399 ... 7.68038511 4.37152481 0.827931404]
 [0.260403425 0.151547506 0.0875201747 ... 6.36936 3.12169528 4.96054363]
 [2.5901475 0.000273428712 2.77036643 ... 1.71886265 0.24741599 0.28116551]]
Epoch 35 Loss None
Time taken for 1

Epoch 49 Loss None
Time taken for 1 epoch 135.5616455078125 sec

[[9.27481651 7.78537798 8.06603241 ... 6.86182213 1.84759879 0.864266038]
 [0.623134315 9.11847 6.84928846 ... 6.70242739 4.32001 7.20207834]
 [9.43704796 6.29036713 4.80040741 ... 3.14566803 0.0312452633 1.76340246]
 ...
 [0.172502458 6.18446064 4.65419531 ... 9.38243484 4.08130932 0.102200873]
 [0.00929268356 0.124446154 0.0157826785 ... 6.14677715 3.56203556 0.764049768]
 [0.740335882 6.30597278e-05 0.454891205 ... 0.0866782814 0.0416621715 1.11246753]]
Epoch 50 Loss None
Time taken for 1 epoch 135.32243299484253 sec

[[10.3596964 7.63938904 6.47234964 ... 7.80893373 2.06534052 1.33260858]
 [2.85034204 9.18332195 7.83741045 ... 6.66397572 3.41698265 7.54415035]
 [10.7734299 5.39744377 3.82762599 ... 3.6511929 0.0240314286 1.00617564]
 ...
 [0.111885965 6.07750273 4.30473566 ... 8.30818176 2.98718667 0.10035938]
 [0.012849981 0.197011024 0.116781704 ... 6.90102196 4.7342782 1.21539402]
 [0.405259579 9.90580156e-05 1.752

Epoch 65 Loss None
Time taken for 1 epoch 135.03444290161133 sec

[[10.4122305 7.15050602 6.47229338 ... 7.18752 3.99770665 0.0197196268]
 [1.72112703 10.4997082 6.13442707 ... 7.36439466 4.53858471 7.37619257]
 [9.47771931 3.09319615 2.75178123 ... 3.91298103 5.09010715e-05 1.32013035]
 ...
 [0.867741227 4.35063505 1.95216739 ... 7.20073223 1.40514982 0.523535907]
 [0.168069184 0.108608477 0.00245864689 ... 6.78450298 1.58764172 0.163470194]
 [0.12810345 9.05986508e-06 0.00380458962 ... 0.0281166919 0.000216818196 0.140537828]]
Epoch 66 Loss None
Time taken for 1 epoch 135.24592471122742 sec

[[10.6875095 6.43187237 5.25096226 ... 5.53878593 3.87967277 0.0285511222]
 [0.153848872 12.5371227 6.71204329 ... 7.04724598 3.94251084 7.14724064]
 [8.68725681 2.50571036 4.44427443 ... 4.33750153 0.00042953802 0.197232425]
 ...
 [0.0675826 5.24688482 3.53286505 ... 4.32572556 1.06738257 1.80652785]
 [0.688834548 0.661246538 0.000713808811 ... 7.13871098 2.9209013 1.96167922]
 [0.121148288 7.23

Epoch 81 Loss None
Time taken for 1 epoch 135.62055706977844 sec

[[12.5661373 5.98789597 6.28700733 ... 4.93475103 0.615445 0.0327114575]
 [2.01439881 8.56907654 6.33239937 ... 5.5698185 3.65132093 6.88001156]
 [9.41686249 2.62578273 5.13273954 ... 4.30935287 4.45832811e-05 0.922566891]
 ...
 [0.00122067309 5.49055433 1.08028603 ... 9.23269272 0.482168496 0.602173924]
 [0.211141631 0.552545667 0.0211204048 ... 5.27969313 1.87648582 0.356915861]
 [0.0259053465 1.54971951e-06 0.0192356203 ... 0.0607858375 0.00171704614 2.0340457]]
Epoch 82 Loss None
Time taken for 1 epoch 135.1233696937561 sec

[[10.7696495 6.75696516 4.50255299 ... 5.46024704 0.292853057 0.332500815]
 [3.76132226 9.16639137 5.00061607 ... 7.01388264 3.98173547 7.93031263]
 [6.73485374 6.78046513 4.92703533 ... 4.94815922 0.000234695544 0.175763503]
 ...
 [0.00165908912 3.60679364 0.165593594 ... 6.22152901 0.589574158 0.109303564]
 [0.0110855876 0.144498438 1.61444807 ... 6.63944435 1.25630331 0.163056374]
 [0.409533 0

Epoch 97 Loss None
Time taken for 1 epoch 134.71380352973938 sec

[[14.5074234 8.12173843 5.26813 ... 4.24125767 1.41077602 0.128848]
 [0.903470218 8.73174477 7.85642099 ... 6.93211842 5.07308292 7.54987144]
 [9.90235806 0.550830901 3.32361531 ... 3.70658374 2.4437606e-05 0.0344924964]
 ...
 [0.251345277 3.82529593 0.0758213177 ... 6.27223063 1.8364445 0.0963227525]
 [0.00387144741 0.957818031 0.25809 ... 6.28426313 0.894026279 0.57931304]
 [0.0456526093 0 0.0379222855 ... 0.0133922547 2.1219028e-05 0.412231773]]
Epoch 98 Loss None
Time taken for 1 epoch 134.96287298202515 sec

[[11.6491051 6.99711323 4.80174446 ... 5.91406584 1.70176971 0.0424852297]
 [3.21756029 8.19845581 8.81062889 ... 7.51279926 3.65440607 7.01605892]
 [12.0256834 5.10405493 3.41457748 ... 3.88314223 5.00666465e-05 2.12327]
 ...
 [0.00430834712 3.88858557 2.11438918 ... 5.42504787 0.63447541 0.0751115158]
 [0.00551405409 0.185643107 0.00157756277 ... 7.34040642 0.975892663 1.08118379]
 [0.122378498 0 0.301989704 .

In [28]:
# 1000 epoch, batchsize 12, 18234 vocab, appox 20 hours



# Predict

In [40]:
tf.train.latest_checkpoint(checkpoint_dir)
#tf.train.load_checkpoint(checkpoint_dir+"/ckpt_150.index")
with open ('char2idx', 'rb') as fp:
    char2idx = pickle.load(fp)
with open ('idx2char', 'rb') as fp:
    idx2char = pickle.load(fp)

In [41]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1, None]))

ValueError: Shapes (31184, 256) and (31410, 256) are incompatible

In [42]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (1, None, 256)            7983104   
_________________________________________________________________
gru_3 (GRU)                  (1, None, 256)            394752    
_________________________________________________________________
lstm_3 (LSTM)                (1, None, 1024)           5246976   
_________________________________________________________________
dense_3 (Dense)              (1, None, 31184)          31963600  
Total params: 45,588,432
Trainable params: 45,588,432
Non-trainable params: 0
_________________________________________________________________


In [43]:
def predict(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 300

  # Converting our start string to numbers (vectorizing)
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.9

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a multinomial distribution to predict the word returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted word as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)
       
      text_generated.append(" "+idx2char[predicted_id])

  return (start_string + ''.join(text_generated))

In [44]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (1, None, 256)            7983104   
_________________________________________________________________
gru_3 (GRU)                  (1, None, 256)            394752    
_________________________________________________________________
lstm_3 (LSTM)                (1, None, 1024)           5246976   
_________________________________________________________________
dense_3 (Dense)              (1, None, 31184)          31963600  
Total params: 45,588,432
Trainable params: 45,588,432
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(predict(model, start_string=u''))